<form action="index/time" method="post">
    <select class="mx-2" name="country" id="country">
        <?php
        $txt = "<option value=''>-Select-</option>";
        foreach ($this->config as $key => $value) {
            echo "<option name=\"$key\" value=" . $key . ">" . $key . "</option>";
        }
        ?>
    </select>
    <input type="submit" value="Submit" class = 'btn btn-secondary'>
</form>
